name: Deploy Portfolio (DEV & PROD)

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: write

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'
          channel: stable

      - run: flutter config --enable-web
      - run: flutter clean
      - run: flutter pub get

      - name: Build DEV
        run: |
          flutter build web \
            --release \
            --base-href="/${{ github.event.repository.name }}/dev/" \
            --dart-define=ENV=dev \
            --dart-define=BUILD_VERSION=${{ github.run_number }}

      - name: Deploy DEV
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
          destination_dir: dev
          keep_files: true


  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'
          channel: stable

      - run: flutter config --enable-web
      - run: flutter clean
      - run: flutter pub get

      - name: Build PROD
        run: |
          flutter build web \
            --release \
            --base-href="/${{ github.event.repository.name }}/" \
            --dart-define=ENV=prod \
            --dart-define=BUILD_VERSION=${{ github.run_number }}

      - name: Deploy PROD
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
          destination_dir: .
          keep_files: true
